language: php

php:
  - '7.3'

services:
  - postgresql

before_script:
  - psql -c "CREATE USER formadytho WITH PASSWORD 'db_password';" -U postgres
  - psql -c "CREATE DATABASE formadytho;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE formadytho TO formadytho;" -U postgres

env:
    - DATABASE_URL="mysql://formadytho:db_password@127.0.0.1:5432/formadytho"

script:
   - composer install
   - php bin/console doctrine:migrations:migrate -n
   - php bin/console doctrine:fixtures:load -q
   - php bin/phpunit
